espcn:
  scale: 4
  channel: 3
  image_weight: 1
  feature_weight: 0.1  # perceptual loss

batch: 64
patch_size: 96
lr: 1.0e-2
lr_decay:
    method: multistep
    decay_step: [50, 75]
    decay_rate: 0.1
