language: python
python:
#  - "2.7"
  - "3.6"
cache: pip

install:
  - pip install tensorflow
  - pip install google-api-python-client oauth2client
  - pip install -e .
script:
  - pytest UTest -v
  - bash UTest/training_test.sh
