# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:

- job: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
      pip install -q tensorflow google-api-python-client oauth2client
      pip install -q https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl
      pip install -U -q -e .
    displayName: 'Install dependencies'

  - script: |
      pytest -v UTest/correlation_test.py UTest/dataset_test.py UTest/virtualfile_test.py --disable-warnings
      pytest -v UTest/image_test.py --disable-warnings
      pytest -v UTest/loader_test.py --disable-warnings
      pytest -v UTest/motion_test.py --disable-warnings
      pytest -v UTest/noise_test.py --disable-warnings
      pytest -v UTest/vgg_test.py --disable-warnings
      pytest -v UTest/training_test.py --disable-warnings
    displayName: 'test with pytest'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()
    enabled: false
