lapgan:
  name: "lapGAN"
  filters: 64
  layers: 20
  norm: "null"
  phase: "G" 
  patch_size: 128
  weight_decay: 0
  l1_weight: 0
  vgg_weight: 1
  gan_weight: 0.01
  scale: 4
  channel: 3
batch: 16
lr: 1.0e-4
